Repository googleapis/google-p12-pem, pull requests merged in 2021-07, with the labels that each got.

#340 chore: skip release-please for owlbot templates
  owlbot.py
Labels: automerge, cla: yes

#342 build: add sync-repo-settings so we can configure for multiple branches
  .github/sync-repo-settings.yaml
Labels: cla: yes

#343 build: configure branch 2.x as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: cla: yes

#344 ci(2.x): copy GitHub actions workflows from default branch
  .github/workflows/ci.yaml
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  package.json
Labels: automerge, cla: yes

#341 fix(deps): update node-forge to 0.10.0
  package.json
Labels: automerge, cla: yes

#346 build: configure branch 1.x as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: cla: yes

#347 ci(1.x): fix ci config
  .github/workflows/ci.yaml
  .kokoro/presubmit/node12/common.cfg
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  .kokoro/presubmit/node12/test.cfg
  package.json
Labels: cla: yes

#350 build: allow release-please to tag releases
  .github/release-please.yml
Labels: cla: yes

#348 fix(deps): update node-forge to 0.10.0
  package.json
Labels: cla: yes

#355 fix(build): use updated repository URL
  .github/ISSUE_TEMPLATE/bug_report.md
  package.json
Labels: automerge, cla: yes

#353 ci: run system/samples tests on node 8
  .kokoro/presubmit/node12/common.cfg
Labels: cla: yes, samples
